### ISSUE TITLE
为何还是需要wiki_100.utf8?

### ISSUE THREAD

**Issue by HwJhx** [yumath/bertNER#1]
您好，为何代码中依然需要word2vec训练的wiki_100.utf8文件？我的理解是：bert是用来替换word2vec做特征抽取，chinese_L-12_H-768_A-12这个中文预训练模型不是用来替代wiki_100.utf8的吗？谢谢！

**Comment by yumath** [comment]
不好意思，暂时还没有空移除代码中读取wiki_100的部分。所以，代码虽然读取了wiki_100，但并未将其应用到embedding的lookup table中。后续有空的时候，会将项目中的无用代码删除。

**Comment by yumath** [comment]
> 您好，为何代码中依然需要word2vec训练的wiki_100.utf8文件？我的理解是：bert是用来替换word2vec做特征抽取，chinese_L-12_H-768_A-12这个中文预训练模型不是用来替代wiki_100.utf8的吗？谢谢！

你的理解是对的，bert替换了原来的基于wiki的embedding

**Comment by HwJhx** [comment]
那是不是文件目录中不需要wiki_utf8 这个文件呢？发自我的华为手机-------- 原始邮件 --------主题：Re: [yumath/bertNER] 为何还是需要wiki_100.utf8? (#1)发件人：longfish 收件人：yumath/bertNER 抄送：HwJhx ,Author 
您好，为何代码中依然需要word2vec训练的wiki_100.utf8文件？我的理解是：bert是用来替换word2vec做特征抽取，chinese_L-12_H-768_A-12这个中文预训练模型不是用来替代wiki_100.utf8的吗？谢谢！

你的理解是对的，bert替换了原来的基于wiki的embedding

**Comment by yumath** [comment]
需要，代码某些位置需要文件存在

**Comment by yumath** [comment]
需要wiki_100是因为train时，main.py的第121行，需要使用wiki_100来构建词典。我暂时还未更改这里构建char_to_id的方式。训练完成后，可以将wiki_100删除。

**Comment by yumath** [comment]
我已经删除了代码中关于wiki等，预训练词嵌入的相关部分。I gonna close this issue
