### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by CodeStuart** [yumath/bertNER#12]
How long has your program been running on your dataset?

**Comment by yumath** [comment]
@CodeStuart You mean training? I don't remember exactly, but it is not too long, about twenty minutes on my GTX 1080 Ti.

**Comment by CodeStuart** [comment]
Excuse me, what does this row represent? Will he be involved in calculating my index
![image](https://user-images.githubusercontent.com/37894906/70527411-d61cca00-1b86-11ea-91b8-cb4cec185530.png)

**Comment by yumath** [comment]
https://github.com/yumath/bertNER/issues/9#issuecomment-539275952
No, it is [SEP] at rear of sentences. Due to some sentence longer than MAX_SEQ_LENGTH, it will be cut by MAX_SEQ_LENGTH, and padding with a [SEP] tag that represents end of sentence.
