### ISSUE TITLE
项目引用格式

### ISSUE THREAD

**Issue by ImGroos** [yumath/bertNER#17]
您好！在研究中借助了您发布的这一项目完成了部分实验，请问您可以提供该项目的引用格式嘛？如果不需要引用您的文章的话，我就按照电子文档的格式引用这一项目，您看可以吗？

**Comment by yumath** [comment]
> 您好！在研究中借助了您发布的这一项目完成了部分实验，请问您可以提供该项目的引用格式嘛？如果不需要引用您的文章的话，我就按照电子文档的格式引用这一项目，您看可以吗？

可以
