### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib' 

### ISSUE THREAD

**Issue by xiaokai01** [yumath/bertNER#19]
ModuleNotFoundError: No module named 'tensorflow.contrib' 
这个不是1.8之后都没有了吗？

**Comment by yumath** [comment]
@xiaokai01 具体不太清楚，我的1.12是没有问题的。
> Because of TensorFlow 2.x module deprecations (for example, tf.flags and tf.contrib), some changes can not be worked around by switching to compat.v1. Upgrading this code may require using an additional library (for example, absl.flags) or switching to a package in tensorflow/addons.

https://www.tensorflow.org/guide/upgrade#compatibility_modules
