### ISSUE TITLE
预测代码问题

### ISSUE THREAD

**Issue by Yusei37** [yumath/bertNER#2]
bert_embedding中is_training=True（model.py 97行）, 在预测的时候也是True，意味着预测的时候，模型也在训练？每次预测结果可能不一样，这是我的理解

**Comment by yumath** [comment]
但是参数不会更新啊，在model.py的83行，只更新fine-tune层的参数，bert的参数是不更新的。

**Comment by yumath** [comment]
> bert_embedding中is_training=True（model.py 97行）, 在预测的时候也是True，意味着预测的时候，模型也在训练？每次预测结果可能不一样，这是我的理解

我偷了个懒，这里确实应该加个判断的。谢谢
