### ISSUE TITLE
What is the use of the .dev file in data？

### ISSUE THREAD

**Issue by iE-zhi** [yumath/bertNER#20]
What is the use of the .dev file in data？

**Comment by yumath** [comment]
@iE-zhi to choose a good model on the dev

**Comment by huaxiaolu** [comment]
Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12/bert_model.ckpt
我有这个问题 然后看到网上一些人跑这个项目遇到了相同的问题 请问你能帮助我们吗

**Comment by huaxiaolu** [comment]
我已经按照说明下载了google的预训练模型并且解压 但是还是出现了这个问题
