### ISSUE TITLE
ner_predict.utf8预测结果的问题

### ISSUE THREAD

**Issue by Janeey99** [yumath/bertNER#21]
在测试集上测试的时候，输出的ner_predict.utf8文件，每句话的最后一个词的gold是[SEP] 预测也是[SEP] 这好像不对吧 最后一个词也有可能是某一实体的一部分，这个要怎么修改啊？还是说这是正确的？大部分情况下，每句话的最后一个字是标点符号，这个倒是没多大影响，但也存在最后一个字不是标点符号的情况，这样预测不对吧？是我哪部分做错了吗？
![image](https://user-images.githubusercontent.com/44643409/103131290-248dff80-46db-11eb-8fd8-5499b3fbbe86.png)
![image](https://user-images.githubusercontent.com/44643409/103131329-4f785380-46db-11eb-8f21-0596e3d9264c.png)

**Comment by yumath** [comment]
@BoomBaYang [SEP]是BERT中的符号，用于表示sentence间的分隔符，会在一条完整的sentence结尾添加一个[SEP]符号表示句子结束。
你有修改代码吗？如果没有的话，可能的原因是你sentence的长度超过了超参max_seq_len，原sentence被截断为max_seq_len - 1，在最后append [SEP]，在解码的时候，把最后一位标记截断。因为要对投入BERT的sentence做字符转换的保护，必然会将最后一位的标记设置为[SEP]。
你可以试一下把max_seq_len增大一点，256或512，但这样会降低模型的解码速度。
另外一种方法就是你自己调整一下训练&测试数据的长度，控制到max_seq_len以下。

**Comment by Janeey99** [comment]
原来是这样，我把max_seq_len设置的太小了。谢谢你的回答！
