### ISSUE TITLE
 lstm_outputs = self.biLSTM_layer(lstm_inputs, self.lstm_dim, self.lengths)为什么 lstm_outputs的维度是（？，？，786）这里的问号为什么不是实数呢？）

### ISSUE THREAD

**Issue by yuelianghexingxing** [yumath/bertNER#28]
这里的问号为什么不是实数呢？

**Comment by yumath** [comment]
@yuelianghexingxing 因为不需要关注

**Comment by yuelianghexingxing** [comment]
如果我想加个注意力机制怎么办呢

**Comment by yumath** [comment]
@yuelianghexingxing 你加一层就可以

**Comment by yuelianghexingxing** [comment]
你好大佬，真的不知道怎么加了，能加个联系方式吗？企鹅：2795086415




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yumath/bertNER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yumath/bertNER]  lstm_outputs = self.biLSTM_layer(lstm_inputs, self.lstm_dim, self.lengths)为什么 lstm_outputs的维度是（？，？，786）这里的问号为什么不是实数呢？） (#28)





 
@yuelianghexingxing 你加一层就可以
