### ISSUE TITLE
用其他数据集跑，因为数据集标签不同，报错“ KeyError: 'B-Project' ”，请问如何解决？

### ISSUE THREAD

**Issue by ddsxhyss** [yumath/bertNER#29]
原数据集标签为ORG、PER、LOC，我用的另外一个数据集，标签不同于原数据集，有一个“Project”的标签。执行“python train.py”时会报错（KeyError: 'B-Project'），请问如何修改代码呢？

**Comment by ddsxhyss** [comment]
原因：用数据集的极小量的一部分测试能否跑通，结果project的标签只在test中存在，train和dev中的数据都不存在这个标签。源代码中应该是有一个检测的过程，检测到test中的标签在train中没有，所以报错。

**Comment by zsh123123** [comment]
更换数据集，遇到了assert len(word) >= 2, print([word[0]])  AssertionError: None 报错，请问是什么原因？ 更换数据除了更换路径还需要改什么代码嘛？
