### ISSUE TITLE
请教一下：如果想训练新的实体，只要在data里面直接增加就可以？另外可以批量predict吗？

### ISSUE THREAD

**Issue by muzier** [yumath/bertNER#7]
请教一下：如果想训练新的实体，只要在data里面直接增加就可以？另外可以批量predict吗？

**Comment by yumath** [comment]
可以批量预测，需要自己修改接口。源码都公布了。

**Comment by yumath** [comment]
是的，新的标记可以直接在数据中添加

**Comment by mingxixixi** [comment]
> 请教一下：如果想训练新的实体，只要在data里面直接增加就可以？另外可以批量predict吗？

你的可以进行批量预测了吗

**Comment by wangjiaxu** [comment]
> > 请教一下：如果想训练新的实体，只要在data里面直接增加就可以？另外可以批量predict吗？
> 
> 你的可以进行批量预测了吗

批量预测的代码可以补充一下吗？
