### ISSUE TITLE
为什么执行python train.py之后没有反应？

### ISSUE THREAD

**Issue by muzier** [yumath/bertNER#8]
博主，为什么执行python train.py之后没有反应啊？会报一个
“bert\tokenization.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.“的warning，然后就退出了，没有报其他错，很奇怪。。。。

**Comment by yumath** [comment]
可能是环境问题，别人没有反应遇到这个错误。我的环境是python3+tensorflow-1.12
