### ISSUE TITLE
有个空白的项是什么？

### ISSUE THREAD

**Issue by lichunnan** [yumath/bertNER#9]
我在训练的时候总有一项是空白的，不知道这是什么。大佬能指点下么？
![image](https://user-images.githubusercontent.com/33343461/65841657-5b019100-e357-11e9-8a1b-dab88b2af91b.png)
还有第一个accuracy是什么？后面是准确率，召回率和F1值我大概知道，这个accuracy是什么指标啊？

**Comment by yumath** [comment]
空白项是BERT在截断长度大于MAX_SEQ_LENGTH的句子的时候，会有一个[SEP]的标记留在句尾，会形成标记。但这个标记在标记映射中没有值，所以为空。
Accuracy就是标记正确率

**Comment by lichunnan** [comment]
十分感谢！不过我们实验室大神讲，bert本身是个很好的利用attention的模型，其实很多fine-tune没必要在bert上加很复杂的模型，比如NER只加一个简单的线性或crf性能可能就很好，你通过实验对这个有什么体会么？

**Comment by yumath** [comment]
@lichunnan 确实，只不过我实验的时候，可能超参数没调好。只用一层全连接fine-tune的时候，不太收敛，相比之下LSTM要容易训练一些。我用过官方给的接口，只加一层全连接，效果和LSTM相差无几
